base_url = "https://dip.tools"
title = "dip"
description = "Write cross-platform application with React-like declarative UI framework and scalable ECS architecture all in Rust."
build_search_index = true

[markdown]
highlight_code = true
external_links_target_blank = true

[extra]
version = "0.1.0"
