base_url = "https://bevydioxus.com"
title = "bevy_dioxus"
description = "Write cross-platform application with React-like declarative UI framework and scalable ECS architecture all in Rust."
default_language = "en"
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true

[extra]
